general:
  # startup_commands: ['shell-exec zebar']
  # shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']
  config_reload_commands: []

  focus_follows_cursor: false
  toggle_workspace_on_refocus: false

  cursor_jump:
    enabled: true
    trigger: 'window_focus' # 'window_focus', 'monitor_focus'

  hide_method: 'hide' # 'cloak', 'hide'
  show_all_in_taskbar: true

gaps:
  scale_with_dpi: true
  inner_gap: '6px'
  outer_gap:
    top: '6px'
    right: '6px'
    bottom: '6px'
    left: '6px'

  single_window_outer_gap:
    top: '0px'
    right: '0px'
    bottom: '0px'
    left: '0px'

window_effects:
  focused_window:
    border:
      enabled: true 
      color: '#000000'
    hide_title_bar:
      enabled: false 
    corner_style:
      enabled: true
      style: 'square' # 'square', 'rounded', 'small_rounded'
    transparency:
      enabled: false 
      opacity: "98%"

  other_windows:
    border:
      enabled: true 
      color: '#000000'
    hide_title_bar:
      enabled: false 
    corner_style:
      enabled: true
      style: 'square' # 'square', 'rounded', 'small_rounded'
    transparency:
      enabled: false 
      opacity: "98%"

window_behavior:
  initial_state: 'tiling'
  state_defaults:
    floating:
      centered: true
      shown_on_top: true
    fullscreen:
      maximized: false 
      shown_on_top: true

workspaces:
  # +-----+ +-----+ +-----+
  # |  0  | |  1  | |  2  |
  # +-----+ +-----+ +-----+
  - name: '1'
    bind_to_monitor: 1
    keep_alive: true
  - name: '2'
    bind_to_monitor: 1
    keep_alive: true
  - name: '3'
    bind_to_monitor: 1
    keep_alive: true
  - name: '4'
    bind_to_monitor: 1
    keep_alive: true
  - name: '5'
    bind_to_monitor: 1
    keep_alive: true
  - name: '6'
    bind_to_monitor: 1
    keep_alive: false
  - name: '7'
    bind_to_monitor: 1 
    keep_alive: false
  - name: '8'
    bind_to_monitor: 1 
    keep_alive: true
  - name: '9'
    bind_to_monitor: 1
    keep_alive: true
  - name: '0'
    bind_to_monitor: 1
    keep_alive: true
  - name: 'left'
    bind_to_monitor: 0
    keep_alive: true
  - name: 'right'
    bind_to_monitor: 2
    keep_alive: true

window_rules:
  # main monitor
  - commands: ["move --workspace 5"]
    match:
      - window_process: { regex: "Spotify" }
  - commands: ["move --workspace 4"]
    match:
      - window_process: { regex: "steam|EpicGamesLauncher" }
  - commands: ["move --workspace 3"]
    match:
      - window_process: { regex: "brave|chrome|Arc|zen" }

  # second monitor
  - commands: ["move --workspace left"]
    match:
      - window_process: { regex: "Discord|ms-teams" }
  - commands: ['set-title-bar-visibility hidden']
    match:
      # - window_process: { equals: 'AfterFX' }
      - window_process: { equals: 'neovide' }
      - window_process: { equals: 'White Knuckle' }
      - window_process: { equals: 'blender' }
  - commands: ['adjust-borders --top 31 --right 0 --bottom 0 --left 0']
    match:
      - window_title: { regex: 'Adobe After Effects*'}
      - window_title: { regex: 'Adobe Premiere Pro*'}
      - window_process: { equals: 'blender' }
  - commands: ['adjust-borders --top 40 '] # chromium apps
    match:
      - window_title: { regex: '美加狮驱动程序 - FIERCE GAMING GEAR | MADLIONS'}

  - commands: ['ignore']
    match:
      - window_class: { equals: 'RAIL_WINDOW' }                           # WSLg workaround
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }               # Ignores picture-in-picture windows for browsers
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }
      - window_title: { regex: 'Arc picture in picture' }
      # - window_process: { equals: 'cs2' }
      - window_process: { equals: 'buttery-taskbar' }
      - window_process: { equals: 'ForzaHorizon5' }
      - window_process: { regex: '*Command Palette*' }
      - window_process: { equals: "OpenTabletDriver.UX.Wpf" }
      - window_title: { regex: "OpenTabletDriver.*" }
      - window_process: { equals: 'zebar' } 
        # window_title: { equals: "Zebar - cinnamon/cinnamon" }
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }
  - commands: ['set-tiling']
    match:
      - window_process: { equals: 'ida' }
        window_title: { regex: 'IDA - .*\\.i64 \\(.*\\).*' }
  - commands: ['set-floating']
    match:
      - window_process: { equals: 'prismlauncher' }
      - window_process: { equals: 'osu!' }
      - window_process: { equals: 'mayhemC-x86_64-SSE4-AVX2' }
      - window_process: { equals: 'Telegram' }
      - window_process: { equals: 'vlc' }
      - window_process: { equals: 'Microsoft.CmdPal.UI' }
      - window_process: { equals: 'Obsidian' }
      - window_process: { equals: 'Microsoft' }
        window_title: { regex: '.*Command Palette.*' }
      - window_process: { equals: 'ida' }
      - window_process: { equals: 'CrosshairX' }
      - window_process: { equals: 'rpcs3' }
      # - window_process: { equals: 'explorer' }
      - window_process: { equals: 'AdGuardVpn' }
      - window_process: { equals: 'Windscribe' }
      - window_process: { equals: 'nvcplui' }
      - window_process: { equals: 'obs64' }
      - window_process: { equals: 'Taskmgr' }
      - window_title: { equals: "Friends List" }
        window_class: { regex: "SDL_app|Chrome_WidgetWin_.*" }
 
  # - commands: ['set-tiling']
  #   match:

  - commands: ['set-fullscreen']
    match:
      - window_process: { equals: 'Telegram' }
        window_title: { equals: 'Media viewer' }

  # - commands: ['set-fullscreen']
  #   match:
  #     - window_process: { equals: 'mpv' }
  
binding_modes:
  - name: 'resize'
    keybindings:
      - commands: ['resize --width -2%']
        bindings: ['h', 'left']
      - commands: ['resize --width +2%']
        bindings: ['l', 'right']
      - commands: ['resize --height +2%']
        bindings: ['k', 'up']
      - commands: ['resize --height -2%']
        bindings: ['j', 'down']
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape', 'enter']

keybindings:
  - commands: ['shell-exec sudo taskkill /f /im whkd.exe; Start-Process whkd -WindowStyle hidden']
    bindings: ['ctrl+alt+shift+r'] # Restarts the 'whkd' process if its starts acting up 
